using UnityEngine;

namespace Ragnarok
{
    public sealed class AdjustSettings : MonoBehaviour, IAdjustTrackingKeys
    {
        public static IAdjustTrackingKeys trankingKeys;

        [SerializeField] string tutorial01_Synopsis;
        [SerializeField] string tutorial02_Move;
        [SerializeField] string tutorial03_Stranger_start;
        [SerializeField] string tutorial04_FirstSharevice;
        [SerializeField] string tutorial05_Stranger_end;
        [SerializeField] string reward_Attendance_Day1;
        [SerializeField] string quest1;
        [SerializeField] string quest2;
        [SerializeField] string quest3;
        [SerializeField] string quest4;
        [SerializeField] string quest5;
        [SerializeField] string quest6;
        [SerializeField] string quest7;
        [SerializeField] string quest8;
        [SerializeField] string quest9;
        [SerializeField] string quest10;
        [SerializeField] string quest11;
        [SerializeField] string quest12;
        [SerializeField] string quest13;
        [SerializeField] string quest14;
        [SerializeField] string quest15;
        [SerializeField] string quest16;
        [SerializeField] string quest17;
        [SerializeField] string quest18;
        [SerializeField] string quest19;
        [SerializeField] string quest20;
        [SerializeField] string quest66;
        [SerializeField] string baselevel1;
        [SerializeField] string baselevel2;
        [SerializeField] string baselevel3;
        [SerializeField] string baselevel4;
        [SerializeField] string baselevel5;
        [SerializeField] string baselevel6;
        [SerializeField] string baselevel7;
        [SerializeField] string baselevel8;
        [SerializeField] string baselevel9;
        [SerializeField] string baselevel10;
        [SerializeField] string baselevel20;
        [SerializeField] string baselevel30;
        [SerializeField] string baselevel40;
        [SerializeField] string baselevel50;
        [SerializeField] string baselevel60;
        [SerializeField] string baselevel70;
        [SerializeField] string baselevel80;
        [SerializeField] string baselevel90;
        [SerializeField] string baselevel100;
        [SerializeField] string baselevel110;
        [SerializeField] string baselevel120;
        [SerializeField] string joblevel1;
        [SerializeField] string joblevel2;
        [SerializeField] string joblevel3;
        [SerializeField] string joblevel4;
        [SerializeField] string joblevel5;
        [SerializeField] string joblevel6;
        [SerializeField] string joblevel7;
        [SerializeField] string joblevel8;
        [SerializeField] string joblevel9;
        [SerializeField] string joblevel10;
        [SerializeField] string joblevel20;
        [SerializeField] string joblevel30;
        [SerializeField] string joblevel35;
        [SerializeField] string joblevel40;
        [SerializeField] string joblevel50;
        [SerializeField] string joblevel60;
        [SerializeField] string joblevel70;
        [SerializeField] string joblevel80;
        [SerializeField] string joblevel90;
        [SerializeField] string joblevel100;
        [SerializeField] string joblevel110;
        [SerializeField] string joblevel120;
        [SerializeField] string facebookLogin;
        [SerializeField] string googleLogin;
        [SerializeField] string appleLogin;
        [SerializeField] string firstAppOpen;
        [SerializeField] string appOpen;
        [SerializeField] string firstJob;
        [SerializeField] string secondJob;
        [SerializeField] string thirdJob;
        [SerializeField] string characterCreate;
        [SerializeField] string firstCharacterOpen;
        [SerializeField] string secondCharacterOpen;
        [SerializeField] string buff;
        [SerializeField] string labyrinthEnter;
        [SerializeField] string labyrinthSingleEnter;
        [SerializeField] string labyrinthMultiEnter;
        [SerializeField] string duel;
        [SerializeField] string infiniteDungeon;
        [SerializeField] string zenyDungeon;
        [SerializeField] string expDungeon;
        [SerializeField] string airshipAssault;
        [SerializeField] string centralLaboratory;
        [SerializeField] string endlessTower;
        [SerializeField] string share;
        [SerializeField] string registerShare;
        [SerializeField] string shareControl;
        [SerializeField] string inAppPurchase;
        [SerializeField] string firstInAppPurchase;
        [SerializeField] string inAppPurchaseRevenue;
        [SerializeField] string card10;
        [SerializeField] string card20;
        [SerializeField] string card30;
        [SerializeField] string card40;
        [SerializeField] string card50;
        [SerializeField] string card60;
        [SerializeField] string card70;
        [SerializeField] string equipment10;
        [SerializeField] string equipment20;
        [SerializeField] string equipment30;
        [SerializeField] string equipment40;
        [SerializeField] string equipment50;
        [SerializeField] string equipment60;
        [SerializeField] string equipment70;

        void Awake()
        {
            trankingKeys = this;
        }

        string IAdjustTrackingKeys.this[TrackType type]
        {
            get
            {
                switch (type)
                {
                    case TrackType.Tutorial01_Synopsis      : return tutorial01_Synopsis;
                    case TrackType.Tutorial02_Move          : return tutorial02_Move;
                    case TrackType.Tutorial03_Stranger_start: return tutorial03_Stranger_start;
                    case TrackType.Tutorial04_FirstSharevice: return tutorial04_FirstSharevice;
                    case TrackType.Tutorial05_Stranger_end  : return tutorial05_Stranger_end;
                    case TrackType.Reward_Attendance_Day1   : return reward_Attendance_Day1;
                    case TrackType.Quest1                   : return quest1;
                    case TrackType.Quest2                   : return quest2;
                    case TrackType.Quest3                   : return quest3;
                    case TrackType.Quest4                   : return quest4;
                    case TrackType.Quest5                   : return quest5;
                    case TrackType.Quest6                   : return quest6;
                    case TrackType.Quest7                   : return quest7;
                    case TrackType.Quest8                   : return quest8;
                    case TrackType.Quest9                   : return quest9;
                    case TrackType.Quest10                  : return quest10;
                    case TrackType.Quest11                  : return quest11;
                    case TrackType.Quest12                  : return quest12;
                    case TrackType.Quest13                  : return quest13;
                    case TrackType.Quest14                  : return quest14;
                    case TrackType.Quest15                  : return quest15;
                    case TrackType.Quest16                  : return quest16;
                    case TrackType.Quest17                  : return quest17;
                    case TrackType.Quest18                  : return quest18;
                    case TrackType.Quest19                  : return quest19;
                    case TrackType.Quest20                  : return quest20;
                    case TrackType.Quest66                  : return quest66;
                    case TrackType.Baselevel1               : return baselevel1;
                    case TrackType.Baselevel2               : return baselevel2;
                    case TrackType.Baselevel3               : return baselevel3;
                    case TrackType.Baselevel4               : return baselevel4;
                    case TrackType.Baselevel5               : return baselevel5;
                    case TrackType.Baselevel6               : return baselevel6;
                    case TrackType.Baselevel7               : return baselevel7;
                    case TrackType.Baselevel8               : return baselevel8;
                    case TrackType.Baselevel9               : return baselevel9;
                    case TrackType.Baselevel10              : return baselevel10;
                    case TrackType.Baselevel20              : return baselevel20;
                    case TrackType.Baselevel30              : return baselevel30;
                    case TrackType.Baselevel40              : return baselevel40;
                    case TrackType.Baselevel50              : return baselevel50;
                    case TrackType.Baselevel60              : return baselevel60;
                    case TrackType.Baselevel70              : return baselevel70;
                    case TrackType.Baselevel80              : return baselevel80;
                    case TrackType.Baselevel90              : return baselevel90;
                    case TrackType.Baselevel100             : return baselevel100;
                    case TrackType.Baselevel110             : return baselevel110;
                    case TrackType.Baselevel120             : return baselevel120;
                    case TrackType.Joblevel1                : return joblevel1;
                    case TrackType.Joblevel2                : return joblevel2;
                    case TrackType.Joblevel3                : return joblevel3;
                    case TrackType.Joblevel4                : return joblevel4;
                    case TrackType.Joblevel5                : return joblevel5;
                    case TrackType.Joblevel6                : return joblevel6;
                    case TrackType.Joblevel7                : return joblevel7;
                    case TrackType.Joblevel8                : return joblevel8;
                    case TrackType.Joblevel9                : return joblevel9;
                    case TrackType.Joblevel10               : return joblevel10;
                    case TrackType.Joblevel20               : return joblevel20;
                    case TrackType.Joblevel30               : return joblevel30;
                    case TrackType.Joblevel35               : return joblevel35;
                    case TrackType.Joblevel40               : return joblevel40;
                    case TrackType.Joblevel50               : return joblevel50;
                    case TrackType.Joblevel60               : return joblevel60;
                    case TrackType.Joblevel70               : return joblevel70;
                    case TrackType.Joblevel80               : return joblevel80;
                    case TrackType.Joblevel90               : return joblevel90;
                    case TrackType.Joblevel100              : return joblevel100;
                    case TrackType.Joblevel110              : return joblevel110;
                    case TrackType.Joblevel120              : return joblevel120;
                    case TrackType.FacebookLogin            : return facebookLogin;
                    case TrackType.GoogleLogin              : return googleLogin;
                    case TrackType.AppleLogin               : return appleLogin;
                    case TrackType.FirstAppOpen             : return firstAppOpen;
                    case TrackType.AppOpen                  : return appOpen;
                    case TrackType.FirstJob                 : return firstJob;
                    case TrackType.SecondJob                : return secondJob;
                    case TrackType.ThirdJob                 : return thirdJob;
                    case TrackType.CharacterCreate          : return characterCreate;
                    case TrackType.FirstCharacterOpen       : return firstCharacterOpen;
                    case TrackType.SecondCharacterOpen      : return secondCharacterOpen;
                    case TrackType.Buff                     : return buff;
                    case TrackType.LabyrinthEnter           : return labyrinthEnter;
                    case TrackType.LabyrinthSingleEnter     : return labyrinthSingleEnter;
                    case TrackType.LabyrinthMultiEnter      : return labyrinthMultiEnter;
                    case TrackType.Duel                     : return duel;
                    case TrackType.InfiniteDungeon          : return infiniteDungeon;
                    case TrackType.ZenyDungeon              : return zenyDungeon;
                    case TrackType.ExpDungeon               : return expDungeon;
                    case TrackType.AirshipAssault           : return airshipAssault;
                    case TrackType.CentralLaboratory        : return centralLaboratory;
                    case TrackType.EndlessTower             : return endlessTower;
                    case TrackType.Share                    : return share;
                    case TrackType.RegisterShare            : return registerShare;
                    case TrackType.ShareControl             : return shareControl;
                    case TrackType.InAppPurchase            : return inAppPurchase;
                    case TrackType.FirstInAppPurchase       : return firstInAppPurchase;
                    case TrackType.InAppPurchaseRevenue     : return inAppPurchaseRevenue;
                    case TrackType.Card10                   : return card10;
                    case TrackType.Card20                   : return card20;
                    case TrackType.Card30                   : return card30;
                    case TrackType.Card40                   : return card40;
                    case TrackType.Card50                   : return card50;
                    case TrackType.Card60                   : return card60;
                    case TrackType.Card70                   : return card70;
                    case TrackType.Equipment10              : return equipment10;
                    case TrackType.Equipment20              : return equipment20;
                    case TrackType.Equipment30              : return equipment30;
                    case TrackType.Equipment40              : return equipment40;
                    case TrackType.Equipment50              : return equipment50;
                    case TrackType.Equipment60              : return equipment60;
                    case TrackType.Equipment70              : return equipment70;
                }

                return string.Empty;
            }
        }
    }
}